engines:
  fixme:
    enabled: true
  golint:
    enabled: true
    checks:
      GoLint/Comments/PackageComments:
        enabled: false
  gofmt:
    enabled: true

ratings:
   paths:
   - "**.go"

exclude_paths:
- "**.got"
- model/*_impl.go
- vendor/**/*
