language: go

sudo: required

go:
- 1.5
- tip

services:
 - docker

notifications:
  email: never

before_install:
- $(! $TRAVIS_SECURE_ENV_VARS) || openssl aes-256-cbc -K $encrypted_e505aa14efb0_key
  -iv $encrypted_e505aa14efb0_iv -in secrets.tar.enc -d | tar xv

deploy:
  provider: gae
  edge:
    source: flowlo/dpl
    branch: gae
  default: true
  docker_build: local
  on:
    branch: dpl
    go: 1.5
