language: go

sudo: required

go:
- 1.5.1
- tip

services:
 - docker

notifications:
  email: never

before_install:
- $(! $TRAVIS_SECURE_ENV_VARS) || openssl aes-256-cbc -K $encrypted_e505aa14efb0_key
  -iv $encrypted_e505aa14efb0_iv -in secrets.tar.enc -d | tar xv

deploy:
  provider: gae
  edge:
    source: flowlo/dpl
    branch: aedeploy
  docker_build: local
  version: staging
  verbosity: debug
  aedeploy: true
  on:
    branch: master
    go: 1.5.1
