application: coduno
version: master
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app

- url: /push
  script: _go_app

- url: /(.+)
  static_files: app/\1
  upload: app/(.+)
  http_headers:
    Strict-Transport-Security: max-age=86400

- url: /
  static_files: app/index.html
  upload: app/index.html
  http_headers:
    Strict-Transport-Security: max-age=86400
