runtime: go
vm: true
api_version: go1

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.8

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60

network:
  instance_tag: "mvm"

resources:
  cpu: .5
  memory_gb: 1.3

handlers:
  - url: /api/.+
    script: _go_app
    secure: always

  - url: /_ah/.+
    script: _go_app
    login: admin

  - url: /dashboard/bower_components/(.+)
    static_files: dashboard/bower_components/\1
    upload: dashboard/bower_components
    secure: always
    expiration: 4d
    http_headers:
      strict-transport-security: max-age=15552000

  - url: /dashboard/(.+)
    static_files: dashboard/app/\1
    upload: dashboard/app
    secure: always
    expiration: 4d
    http_headers:
      strict-transport-security: max-age=15552000

  - url: /dashboard(/|$)
    static_files: dashboard/app/index.html
    upload: dashboard/app/index.html
    secure: always
    expiration: 4d
    http_headers:
      strict-transport-security: max-age=15552000

  - url: /codeground/bower_components/(.+)
    static_files: codeground/bower_components/\1
    upload: codeground/bower_components
    secure: always
    expiration: 4d
    http_headers:
      strict-transport-security: max-age=15552000

  - url: /codeground/(.+)
    static_files: codeground/app/\1
    upload: codeground/app
    secure: always
    expiration: 4d
    http_headers:
      strict-transport-security: max-age=15552000

  - url: /codeground(/|$)
    static_files: codeground/app/index.html
    upload: codeground/app/index.html
    secure: always
    expiration: 4d
    http_headers:
      strict-transport-security: max-age=15552000

  - url: /(.+)
    static_files: web/\1
    upload: web
    secure: always
    expiration: 4d
    http_headers:
      strict-transport-security: max-age=15552000

  - url: /
    static_files: web/index.html
    upload: web/index.html
    secure: always
    expiration: 4d
    http_headers:
      strict-transport-security: max-age=15552000
