application: coduno
version: master
runtime: go
api_version: go1

handlers:
  - url: /api/.+
    script: _go_app
    secure: always

  - url: /(.+)
    static_files: web/\1
    upload: web
    secure: always
    expiration: 4d
    http_headers:
      strict-transport-security: max-age=15552000

  - url: /
    static_files: web/index.html
    upload: web/index.html
    secure: always
    expiration: 4d
    http_headers:
      strict-transport-security: max-age=15552000
