module: api
runtime: go
vm: true
api_version: go1

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.8

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60

network:
  instance_tag: "mvm"

resources:
  cpu: .5
  memory_gb: 1.3
  disk_size_gb: 10

handlers:
  - url: /_ah/.+
    script: _go_app
    login: admin

  - url: /status
    script: _go_app
    login: admin
    secure: always

  - url: /subscriptions
    script: _go_app
    login: admin
    secure: always

  - url: /tokens/collect
    script: _go_app
    login: admin
    secure: always

  - url: /mock.+
    script: _go_app
    login: admin
    secure: always

  - url: /.+
    script: _go_app
    secure: always
