#!/bin/bash

for file in $(git diff --cached --name-only --diff-filter=ACMR -- **/*.go)
do
	# Check for unformatted code
	unformatted=$(gofmt -l $file)
	if [ ! -z "$unformatted" ]
	then
		echo >&2 "Please format:"
		echo >&2 "    gofmt -w -s $PWD/$file"
		exit 1
	fi
done
